#FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210806.v1

FROM mcr.microsoft.com/azureml/base-gpu:openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04

# ENV CUDA_VERSION 10.1

RUN apt-get update 
RUN apt-get install -y unixodbc-dev curl
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

ENV CUDA_VERSION 10.1


# RUN pip install --pre cupy-cuda114

# RUN echo "/usr/local/nvidia/lib" >> ./lib64_output_1 \
#     && echo "/usr/local/nvidia/lib64" >> ./lib64_output

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=9.0"

CMD "nvcc -V" 